/* eslint-disable */
export const ActionType = {
  FETCH_INITIAL_DATA: 'FETCH_INITIAL_DATA',
  GET_LOGIN: 'GET_LOGIN',
  GET_USER: 'GET_USER',
  FETCHED_USER: 'FETCHED_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_ERROR: 'GET_USER_ERROR'
}