/* eslint-disable */
export const ActionType = {
  FETCH_INITIAL_DATA: 'FETCH_INITIAL_DATA',
  SET_LOGIN: 'SET_LOGIN',
  GET_USER_AVATAR: 'GET_USER_AVATAR',
  GET_USER_AVATAR_SUCCESS: 'GET_USER_AVATAR_SUCCESS',
  GET_USER_AVATAR_FAILURE: 'GET_USER_AVATAR_FAILURE',
  SET_TERMINAL: 'SET_TERMINAL',

}